### ISSUE TITLE
lazy load images in events page

### ISSUE THREAD

**Issue by cTxplorer** [fhrf/fhrf.github.io#4]
On [events page](https://fhrf.in/events.html), there are more than 150 event images.

They are all loaded at once; amounting to a size of 17MB.

There should be some lady loading mechanism, by which images are fetched as and when a user scrolls near to image.

In case you are unfamiliar, here's a css-tricks' [guide to lazy loading](https://css-tricks.com/the-complete-guide-to-lazy-loading-images/).

Feel free to try and experiment with a solution that you think will work :)

**Comment by qwerty-rgb** [comment]
i will do it assign me please

**Comment by cTxplorer** [comment]
Alright, assigning this to you, @qwerty-rgb 
Let me know if you face any difficulty :)

**Comment by qwerty-rgb** [comment]
@cTxplorer i went through some material on the internet but have not yet got a fair amount of knowledge what to do
I only got to know that it helps to load the webpages faster and efficient
can u reccomend some things

**Comment by cTxplorer** [comment]
Hey @qwerty-rgb, great work researching the web.

as per my current understanding from [this article](browser-level lazy-loading), there are two ways (both javascript) to lazy load images; using event handles (like a scroll) or using intersection observer API (which tells us if an element is in view or not).

However, browsers have now rolled out native-support for lazy loading, since this is essential functionality. There's a new `loading` attribute which can we used to leverage lazy-loading. Check out this [web.dev article](https://web.dev/browser-level-image-lazy-loading/)

Though, it has supported only in recent browser versions. We can still utilize it rather than adding scroll handlers.

**Comment by agonzalezio** [comment]
Hey @qwerty-rgb , don't hesitate to try to solve this issue; you can [see an implemented solution](https://github.com/sonipranjal/storysea.in/pull/16/commits/b51da6746433148ae583d747944a6011cef12f8e) for lazy loading on my PR.

Since images on this repo are loaded using an ajax request, I don't think adding the `lazy` html attribute on them will work; I'd suggest to first load the markup without sourcing the image and then load each one progressively using intersection observer.

**Comment by cTxplorer** [comment]
@qwerty-rgb any progress/blocker on this? Are you still looking into this?
